# Generated by Django 6.0.4 on 2026-06-05 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacaofisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True, verbose_name='Número')),
                ('peso', models.FloatField(blank=True, null=True, verbose_name='Peso')),
                ('altura', models.FloatField(blank=True, null=True, verbose_name='Altura')),
                ('percentual_gordura', models.FloatField(blank=True, null=True, verbose_name='Percentual gordura')),
                ('massa_magra', models.FloatField(blank=True, null=True, verbose_name='Massa magra')),
                ('imc', models.FloatField(blank=True, null=True, verbose_name='IMC')),
                ('data_avaliacao', models.DateField(auto_now_add=True, verbose_name='Data avaliacao')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacaofisica', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Avaliacao física',
                'verbose_name_plural': 'Avaliações físicas',
                'ordering': ['id'],
            },
        ),
    ]
