# Generated by Django 6.0.4 on 2026-05-31 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('treinadores', '0002_alter_treinador_registrocref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichatreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descricao')),
                ('esta_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinadores.treinador')),
            ],
            options={
                'verbose_name': 'Ficha de Treino',
                'verbose_name_plural': 'Fichas de Treinos',
                'ordering': ['id'],
            },
        ),
    ]
