# Generated by Django 6.0.4 on 2026-05-31 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diatreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.IntegerField(blank=True, default=0, null=True, verbose_name='Serie')),
                ('repeticao', models.IntegerField(blank=True, default=0, null=True, verbose_name='Repeticao')),
                ('intervalo', models.IntegerField(blank=True, default=0, null=True, verbose_name='Intervalo')),
                ('observacao', models.TextField(max_length=200, verbose_name='Descricao')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='exercicios.exercicio')),
            ],
            options={
                'verbose_name': 'Dia de treino',
                'verbose_name_plural': 'Dias de Treinos',
                'ordering': ['id'],
            },
        ),
    ]
