# Generated by Django 6.0.4 on 2026-05-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diastreinos', '0003_alter_diatreino_ficha_treino'),
    ]

    operations = [
        migrations.AddField(
            model_name='diatreino',
            name='nome',
            field=models.CharField(choices=[('A', 'Treino A'), ('B', 'Treino B'), ('C', 'Treino C'), ('D', 'Treino D'), ('E', 'Treino E'), ('F', 'Treino F')], default='A', max_length=1, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
