# Generated by Django 6.0.4 on 2026-05-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diastreinos', '0004_diatreino_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diatreino',
            name='nome',
        ),
        migrations.AddField(
            model_name='diatreino',
            name='dia_treino',
            field=models.CharField(choices=[('A', 'Treino A'), ('B', 'Treino B'), ('C', 'Treino C'), ('D', 'Treino D'), ('E', 'Treino E'), ('F', 'Treino F')], default='A', max_length=1, verbose_name='Dia de Treino'),
            preserve_default=False,
        ),
    ]
