# Generated by Django 6.0.4 on 2026-05-31 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimentos', '0001_initial'),
        ('planosalimentares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_refeicao', models.CharField(choices=[('1', 'Desjejum'), ('2', 'Lanche da Manha'), ('3', 'Almoco'), ('4', 'Lanche da Tarde'), ('5', 'Jantar'), ('6', 'Ceia')], max_length=1, verbose_name='Dia de Refeicao')),
                ('observacao', models.TextField(max_length=200, verbose_name='Descricao')),
                ('quantidade_gramas', models.FloatField(blank=True, default=0, null=True, verbose_name='Quantidade em gramas')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='alimentos.alimento')),
                ('plano_alimentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planosalimentares', to='planosalimentares.planoalimentar')),
            ],
            options={
                'verbose_name': 'Dia de Refeicao',
                'verbose_name_plural': 'Dias de Refeicoes',
                'ordering': ['id'],
            },
        ),
    ]
