# Generated by Django 6.0.4 on 2026-05-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinador',
            name='registroCREF',
            field=models.TextField(max_length=100, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='treinador',
            name='tipo_treinamento',
            field=models.TextField(max_length=100, verbose_name='Descricao'),
        ),
    ]
