# Generated by Django 6.0.4 on 2026-05-31 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diastreinos', '0002_initial'),
        ('fichastreinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diatreino',
            name='ficha_treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichastreinos', to='fichastreinos.fichatreino'),
        ),
    ]
