# Generated by Django 6.0.4 on 2026-05-31 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.pessoa')),
                ('registroCREF', models.CharField(max_length=100, verbose_name='registroCREF')),
                ('tipo_treinamento', models.CharField(max_length=100, verbose_name='tipo_treinamento')),
            ],
            options={
                'verbose_name': 'Treinador',
                'verbose_name_plural': 'Treinadores',
                'ordering': ['id'],
            },
            bases=('pessoas.pessoa',),
        ),
    ]
