# Generated by Django 6.0.4 on 2026-05-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinadores', '0002_alter_treinador_registrocref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinador',
            name='registroCREF',
            field=models.TextField(max_length=100, verbose_name='Registro CREF'),
        ),
        migrations.AlterField(
            model_name='treinador',
            name='tipo_treinamento',
            field=models.TextField(max_length=100, verbose_name='Tipo de Treinamento'),
        ),
    ]
