# Generated by Django 6.0.4 on 2026-05-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fichamedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Ficha Medica',
                'verbose_name_plural': 'Fichas Medicas',
                'ordering': ['id'],
            },
        ),
    ]
