# Generated by Django 6.0.4 on 2026-05-31 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.pessoa')),
                ('registroCRN', models.TextField(max_length=100, verbose_name='Registro CRN')),
                ('abordagem_nutricional', models.TextField(max_length=100, verbose_name='Abordagem Nutricional')),
            ],
            options={
                'verbose_name': 'Nutricionista',
                'verbose_name_plural': 'Nutricionistas',
                'ordering': ['id'],
            },
            bases=('pessoas.pessoa',),
        ),
    ]
