# Generated by Django 6.0.4 on 2026-05-31 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gruposmusculares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descricao')),
                ('esta_ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('foto', models.ImageField(upload_to='fotos', verbose_name='Foto')),
                ('grupomuscular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruposmusculares.grupomuscular')),
            ],
            options={
                'verbose_name': 'Exercicio',
                'verbose_name_plural': 'Exercicios',
                'ordering': ['id'],
            },
        ),
    ]
