# Generated by Django 6.0.4 on 2026-05-31 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoriasalimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descricao')),
                ('porcao_referencia_gramas', models.FloatField(default=100.0, verbose_name='Porção de Referência (g)')),
                ('calorias', models.FloatField(default=0, verbose_name='Calorias')),
                ('proteina', models.FloatField(default=0, verbose_name='Proteina')),
                ('carboidrato', models.FloatField(default=0, verbose_name='Carboidrato')),
                ('gordura', models.FloatField(default=0, verbose_name='Gordura')),
                ('esta_ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('foto', models.ImageField(upload_to='fotos', verbose_name='Foto')),
                ('categoriaalimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoriasalimentos.categoriaalimento')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['id'],
            },
        ),
    ]
